# Generated by Django 6.0 on 2025-12-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='activity_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
