# Generated by Django 6.0 on 2025-12-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_activitylog_activity_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='status',
            field=models.CharField(choices=[('WORKING', 'Working'), ('IDLE', 'Idle'), ('AWAY', 'Away from desk'), ('PHONE_USE', 'Using Phone')], max_length=20),
        ),
    ]
