# Generated by Django 6.0 on 2026-01-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_activitylog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='stream_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='status',
            field=models.CharField(choices=[('WORKING', 'Working'), ('IDLE', 'Idle'), ('AWAY', 'Away from desk')], max_length=20),
        ),
    ]
