# Generated by Django 6.0 on 2026-01-15 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_employee_stream_url_alter_activitylog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='stream_url',
        ),
    ]
